### ISSUE TITLE
"Could Not Find Tiller" on Step 4 after Helm Upgrade command

### ISSUE THREAD

**Issue by SteveSonoa** [Axway/Setup-Amplify-Mesh-Governance#1]
When I try the command "helm upgrade --install istio --namespace istio-system axway/istio -f istioOverride.yaml" there is a pause, then I receive the error "Error: could not find tiller"

![Screen Shot 2019-06-06 at 3 54 52 PM](https://user-images.githubusercontent.com/27326560/59071477-a86f6500-8873-11e9-8920-d3d695f3713d.png)

**Comment by asayah** [comment]
did the helm init in chapter2 went well ? @SteveSonoa

**Comment by SteveSonoa** [comment]
Resolved in step 2.
